#pragma config(Sensor, in1,    s1,             sensorPotentiometer)
#pragma config(Sensor, in2,    s2,             sensorNone)
#pragma config(Sensor, dgtl3,  selector,       sensorDigitalIn)
#pragma config(Sensor, dgtl4,  ifDisco,        sensorDigitalIn)
#pragma config(Sensor, dgtl9,  s3,             sensorQuadEncoder)
#pragma config(Sensor, dgtl11, s4,             sensorQuadEncoder)
#pragma config(Motor,  port2,           d1,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           g1,            tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           l1,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           l2,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           l6,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           l4,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           g2,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           d2,            tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

bool lowPow =  false;

int  clawPos = 0;
bool setPos =  false;

int state = 0;

const int clawHalf = 1430;
const int clawFull = 2820;
bool clawDone =  false;

const int liftBig = 2490;
const int liftSmall = 2160;
const int liftMax = 2690;
const int liftMin = 905;
bool liftDone = false;

int clawVal = SensorValue[s1];
int liftVal = SensorValue[s2];

int leftVal = -SensorValue[s3];
int rightVal = SensorValue[s4];
bool leftDone = true;
bool rightDone = true;

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

void claw(int degree)	{ // Method to adjust claw position with the direction and degree

	int leeway = 50;

	clawVal = SensorValue[s1];

	if(clawVal > degree + leeway)	{ // If claw wants to open

		motor[g1] = -127;
		motor[g2] = -127;

		clawDone = false;

		}	else if (clawVal < degree - leeway)	{ // If claw wants to close

		motor[g1] = 127;
		motor[g2] = 127;

		clawDone = false;

		}	else	{

		motor[g1] = 0;
		motor[g2] = 0;

		clawDone = true;

	}

}

void lift(int degree)	{ // Method to adjust lift arm position by direction of change in rotation

int leeway = 50;

	int currentLiftVal = SensorValue[s2];

	if (currentLiftVal > (degree + leeway))	{

		motor[l1] = -127;
		motor[l2] = -127;

		motor[l4] = -127;
		motor[l6] = -127;


		liftDone = false;

		}	else if (currentLiftVal < (degree - leeway))	{

		motor[l1] = 127;
		motor[l2] = 127;
		motor[l4] = 127;
		motor[l6] = 127;

		liftDone = false;

		}	else	{

		motor[l1] = 0;
		motor[l2] = 0;

		motor[l4] = 0;
		motor[l6] = 0;

		liftDone = true;

	}

}

void drive(int left, int right)	{ // Method which automatically drives the robot

	int leeway = 10;

	int currentL = -SensorValue[s3];
	int currentR = SensorValue[s4];

	if (SensorValue[selector] == 1)	{

		if (currentL > (left + leeway) && !leftDone)	{

			motor[d1] = -127;

			leftDone = false;

			}	else if(currentL < (left - leeway) && !leftDone)	{

			motor[d1] = 127;

			leftDone = false;

			}	else	{

			motor[d1] = 0;

			SensorValue[s3] = 0;
			SensorValue[s4] = 0;

			leftDone = true;

		}

		if (currentR > (right + leeway) && !rightDone)	{

			motor[d2] = -127;

			rightDone = false;

			}	else if(currentR < (right - leeway) && !rightDone)	{

			motor[d2] = 127;

			rightDone = false;

			}	else	{

			motor[d2] = 0;

			SensorValue[s3] = 0;
			SensorValue[s4] = 0;

			rightDone = true;

		}

		}	else	{

		if (currentL > (left + leeway) && !rightDone)	{

			motor[d2] = -127;

			rightDone = false;

			}	else if(currentL < (left - leeway) && !rightDone)	{

			motor[d2] = 127;

			rightDone = false;

			}	else	{

			motor[d2] = 0;

			SensorValue[s3] = 0;
			SensorValue[s4] = 0;

			rightDone = true;

		}

		if (currentR > (right + leeway) && !leftDone)	{

			motor[d1] = -127;

			leftDone = false;

			}	else if(currentR < (right - leeway) && !leftDone)	{

			motor[d1] = 127;

			leftDone = false;

			}	else	{

			motor[d1] = 0;

			SensorValue[s3] = 0;
			SensorValue[s4] = 0;

			leftDone = true;

		}

	}

}

task autonomous()
{

	while(true)	{

		switch (state)	{

		case 0 :

			SensorValue[s3] = 0;
			SensorValue[s4] = 0;

			state++;

			break;

		case 1 :

		if(!clawDone)	{

			claw(clawHalf);

		}

		if(!liftDone)	{

				lift(2820);

			}

			drive(566, 574);

			if (leftDone && rightDone)	{

				state++;

				liftDone = false;
				clawDone = false;

			}

			break;

		case 2 :

			drive(-58, 174);

			if (leftDone && rightDone)	{

				state++;

			}

			break;

		case 3 :

			drive (459, 477);

			if (leftDone && rightDone)	{

				state++;

			}

			break;

		case 4 :

			drive (248, 29);

			if (leftDone && rightDone)	{

				state++;

			}

			break;

		case 5 :

			drive (757, 745);

			if (leftDone && rightDone)	{

				state++;

			}

			break;


		case 6 :

			drive (-920, -933);


			if (leftDone && rightDone)	{

				state++;

			}


			break;


		case 7 :

			lift(911);

			claw(653);

			drive (-58, -1011);

			if (leftDone && rightDone)	{

				state++;

			}

			break;

		case 8 :

			drive(1677,1701);

			if (leftDone && rightDone)	{

				state++;

			}

			break;

		case 9 :

			claw(59);

			if(clawDone)	{

				state++;

			}

			break;

		case 10 :

			lift(2597);

			drive (-815, -892);

			if (leftDone && rightDone)	{

				state++;

			}

			break;

		case 11 :

			drive (738, 1183);

			if (leftDone && rightDone)	{

				state++;

			}

			break;

		case 12 :

			drive (355, 355);

			if (leftDone && rightDone)	{

				state++;

			}

			break;

		case 13 :

			claw(520);

			if(clawDone)	{

				drive(-1225, -1316);

			}
			if (leftDone && rightDone)	{

				state++;

			}

			break;

		case 14 :

			claw(815);

			lift(913);

			drive (139, -196);

			if (leftDone && rightDone)	{

				state++;

			}

			break;

		case 15 :

			claw(815);

			lift(913);

			drive (547, 536);

			if (leftDone && rightDone)	{

				state++;

			}

			break;

		case 16 :

			claw(349);

			if(clawDone)	{

				lift(2600);

				drive (-78, 292);

			}

			if (leftDone && rightDone)	{

				state++;

			}

			break;

		case 17 :

			drive(1208, 1252);

			if (leftDone && rightDone)	{

				state++;

			}

			break;

		case 18 :

			claw(1011);

			break;

		default :

			break;

		}

	}

}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{

	SensorValue[s3] = 0;
	SensorValue[s4] = 0;

	//int driveSpeed = 0;
	//int turnSpeed = 0;
	int driveL = 0, driveR = 0;

	const int threshold = 15;

	while (true)	{

		clawVal = SensorValue[s1];
		liftVal = SensorValue[s2];

		leftVal = -SensorValue[s3];
		rightVal = SensorValue[s4];

		// Two Joystick Drive v2 - BAYAN EDITION

		driveL = vexRT[Ch3];
		driveR = vexRT[Ch2];

		if(abs(driveR) >= threshold)	{

			motor[d1] = driveR;

			}	else {

			motor[d1] = 0;

		}
		if(abs(driveL) >= threshold)	{

			motor[d2] = driveL;

			}else	{


			motor[d2] = 0;

		}

		if(vexRT[Btn6U] == 1)	{

			motor[g1] = 127;
			motor[g2] = 127;

			lowPow = false;

			}	else if(vexRT[Btn6D] == 1)	{

			motor[g1] = -127;
			motor[g2] = -127;

			lowPow = false;

			}	else if (!(lowPow))	{

			motor[g1] = 0;
			motor[g2] = 0;

		}

		if(vexRT[Btn8D] == 1)	{

			lowPow = true;

			motor[g1]	= -60;
			motor[g2]	= -60;

		}

		if (vexRT[Btn5U] == 1)	{

			motor[l1] = 127;
			motor[l2] = 127;

			motor[l4] = 127;
			motor[l6] = 127;

			}	else if (vexRT[Btn5D] == 1)	{

			motor[l1] = -127;
			motor[l2] = -127;

			motor[l4] = -127;
			motor[l6] = -127;

			}	else	{

			motor[l1] = 0;
			motor[l2] = 0;

			motor[l4] = 0;
			motor[l6] = 0;

		}

	}
}
