#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    s1,             sensorPotentiometer)
#pragma config(Sensor, dgtl1,  s2,             sensorQuadEncoder)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port2,           g1,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           d2,            tmotorVex393HighSpeed_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port4,           l3,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           l6,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           l4,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           l1,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           l2,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           d1,            tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, I2C_2)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

int state = 0;

int clawHalf = 1510;
int clawFull = 2820;
bool clawDone =  false;

int liftBig = 88;
int liftSmall = 76;
int liftMax = 118;
bool liftDone = false;

int leftTicks;
int rightTicks;
bool leftDone = false;
bool rightDone = false;
bool driveDone = false;

int clawVal = SensorValue[s1];
int liftVal = SensorValue[s2];

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

void claw(int degree)	{ // Method to adjust claw position with the direction and degree

	clawVal = SensorValue[s1];

	if(clawVal >= degree + 50)	{ // If claw wants to open

		motor[g1] = -127;

		clawDone = false;

		}	else if (clawVal <= degree - 50)	{ // If claw wants to close

		motor[g1] = 127;

		clawDone = false;

		}	else	{

		motor[g1] = 0;

		clawDone = true;

	}

}

void lift(int delta)	{ // Method to adjust lift arm position by direction of change in rotation

	int currentLiftVal = SensorValue[s2];

	if (currentLiftVal > (liftVal + delta + 5))	{

		motor[l1] = -127;
		motor[l2] = -127;
		motor[l3] = -127;
		motor[l4] = -127;
		motor[l6] = -127;


		liftDone = false;

		}	else if (currentLiftVal < (liftVal + delta - 5))	{

		motor[l1] = 127;
		motor[l2] = 127;
		motor[l3] = 127;
		motor[l4] = 127;
		motor[l6] = 127;

		liftDone = false;

		}	else	{

		motor[l1] = 0;
		motor[l2] = 0;
		motor[l3] = 0;
		motor[l4] = 0;
		motor[l6] = 0;

		liftDone = true;

	}

}

void drive(int left, int right)	{ // Method which automatically drives the robot

	leftTicks = nMotorEncoder[d2];

	rightTicks = nMotorEncoder[d1];

	if (leftTicks < left - 2)	{

		motor[d2] = 127;

		leftDone = false;

		}	else if (leftTicks > left + 2)	{

		motor[d2] = -127;

		leftDone = false;

		}	else	{

		motor[d2] = 0;

		leftDone = true;

	}

	if (rightTicks < right - 2)	{

		motor[d1] = 127;

		rightDone = false;

		}	else if (rightTicks > right + 2)	{

		motor[d1] = -127;

		rightDone = false;

		}	else	{

		motor[d1] = 0;

		rightDone = true;

	}

	if (leftDone && rightDone)	{

		driveDone = true;

		}	else	{

		driveDone = false;

	}

}

task autonomous()	{

}

task usercontrol()
{

	state = 0;

	while(true)	{

		switch (state)	{

		case 0 :

			liftVal = SensorValue[s2];

			nMotorEncoder[d1] = 0;
			nMotorEncoder[d2] = 0;

			state++;

			break;

		case 1 :

			claw(clawHalf);

			lift(liftBig);

			leftTicks = nMotorEncoder[d2];
			rightTicks = nMotorEncoder[d1];

			drive(897, 899);

			if (driveDone)	{

				state++;

				nMotorEncoder[d1] = 0;
				nMotorEncoder[d2] = 0;

			}

			break;

		case 2 :

			drive(61, 168);

			if (driveDone)	{

				state++;

				nMotorEncoder[d1] = 0;
				nMotorEncoder[d2] = 0;

			}

		case 3 :

			drive (1151, 1144);

			if (driveDone)	{

				state++;

				nMotorEncoder[d1] = 0;
				nMotorEncoder[d2] = 0;

			}

			break;

		case 4 :

			drive (-410, -414);

			if (driveDone)	{

				state++;

				nMotorEncoder[d1] = 0;
				nMotorEncoder[d2] = 0;

			}

			break;

		case 5 :

			drive (675, -355);

			if (driveDone)	{

				state++;

				nMotorEncoder[d1] = 0;
				nMotorEncoder[d2] = 0;

			}

			break;


		case 6 :

			drive (1365, 1335);

			if (driveDone)	{

				state++;

				nMotorEncoder[d1] = 0;
				nMotorEncoder[d2] = 0;

			}

			break;


		case 7 :

			drive (-433, 524);

			if (driveDone)	{

				state++;

				nMotorEncoder[d1] = 0;
				nMotorEncoder[d2] = 0;

			}

			break;

		case 8 :

			drive (393, 392);

			if (driveDone)	{

				state++;

				nMotorEncoder[d1] = 0;
				nMotorEncoder[d2] = 0;

			}

			break;

		case 9 :

			drive (1032, -740);

			if (driveDone)	{

				state++;

				nMotorEncoder[d1] = 0;
				nMotorEncoder[d2] = 0;

			}

			break;

		case 10 :

			drive (530, 537);

			if (driveDone)	{

				state++;

				nMotorEncoder[d1] = 0;
				nMotorEncoder[d2] = 0;

			}

			break;

		case 11 :

			drive (730, -870);

			if (driveDone)	{

				state++;

				nMotorEncoder[d1] = 0;
				nMotorEncoder[d2] = 0;

			}

			break;

		case 12 :

			drive(796, 801);

			if (driveDone)	{

				state++;

				nMotorEncoder[d1] = 0;
				nMotorEncoder[d2] = 0;

			}

			break;

		case 13 :

			break;

		case 14 :

			break;

		case 15 :

			break;

		default :

			break;

		}

	}

}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/
/*
task usercontrol()
{

	//int driveSpeed = 0;
	//int turnSpeed = 0;
	int driveL = 0, driveR = 0;

	const int threshold = 15;

	while (true)	{

		clawVal = SensorValue[s1];
		liftVal = SensorValue[s2];

		leftTicks = nMotorEncoder[d1];
		rightTicks = nMotorEncoder[d2];

		// Two Joystick Drive v2 - BAYAN EDITION

		driveL = vexRT[Ch3];
		driveR = vexRT[Ch2];

		if(abs(driveR) >= threshold)	{

			motor[d1] = driveR;

			}	else {

			motor[d1] = 0;

		}
		if(abs(driveL) >= threshold)	{

			motor[d2] = driveL;

			}else	{


			motor[d2] = 0;

		}

		if(vexRT[Btn6U] == 1)	{

			motor[g1] = 127;

			}	else if(vexRT[Btn6D] == 1)	{

			motor[g1] = -127;

			}	else	{

			motor[g1] = 0;

		}

		if (vexRT[Btn5U] == 1)	{

			motor[l1] = 127;
			motor[l2] = 127;
			motor[l3] = 127;
			motor[l4] = 127;
			motor[l6] = 127;

			}	else if (vexRT[Btn5D] == 1)	{

			motor[l1] = -127;
			motor[l2] = -127;
			motor[l3] = -127;
			motor[l4] = -127;
			motor[l6] = -127;

			}	else	{

			motor[l1] = 0;
			motor[l2] = 0;
			motor[l3] = 0;
			motor[l4] = 0;
			motor[l6] = 0;

		}

	}
}*/
