#pragma config(Sensor, in1,    s1,             sensorPotentiometer)
#pragma config(Sensor, dgtl1,  s2,             sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  selector,       sensorDigitalIn)
#pragma config(Sensor, dgtl4,  ifDisco,        sensorDigitalIn)
#pragma config(Motor,  port2,           g1,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           d2,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           l3,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           l6,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           l4,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           l1,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           l2,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           d1,            tmotorVex393HighSpeed_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

int state = 0;

int clawHalf = 1510;
int clawFull = 2820;
bool clawDone =  false;

int liftBig = 88;
int liftSmall = 76;
int liftMax = 118;
bool liftDone = false;

int clawVal = SensorValue[s1];
int liftVal = SensorValue[s2];

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

void claw(int degree)	{ // Method to adjust claw position with the direction and degree

	clawVal = SensorValue[s1];

	if(clawVal >= degree + 50)	{ // If claw wants to open

		motor[g1] = -127;

		clawDone = false;

		}	else if (clawVal <= degree - 50)	{ // If claw wants to close

		motor[g1] = 127;

		clawDone = false;

		}	else	{

		motor[g1] = 0;

		clawDone = true;

	}

}

void lift(int delta)	{ // Method to adjust lift arm position by direction of change in rotation

	int currentLiftVal = SensorValue[s2];

	if (currentLiftVal > (liftVal + delta + 5))	{

		motor[l1] = -127;
		motor[l2] = -127;
		motor[l3] = -127;
		motor[l4] = -127;
		motor[l6] = -127;


		liftDone = false;

		}	else if (currentLiftVal < (liftVal + delta - 5))	{

		motor[l1] = 127;
		motor[l2] = 127;
		motor[l3] = 127;
		motor[l4] = 127;
		motor[l6] = 127;

		liftDone = false;

		}	else	{

		motor[l1] = 0;
		motor[l2] = 0;
		motor[l3] = 0;
		motor[l4] = 0;
		motor[l6] = 0;

		liftDone = true;

	}

}

void drive(int left, int right)	{ // Method which automatically drives the robot

	if (SensorValue[selector] == 1)	{

		motor[d2] = left;
		motor[d1] = right;

		}	else	{

		motor[d1] = left;
		motor[d2] = right;

	}

}

task autonomous()
{

	int t = 0;

	while(true)	{

		switch (state)	{

		case 0 :

			liftVal = SensorValue[s2];

			state++;

			break;

		case 1 :

			claw(clawHalf);

			if (!liftDone)	{

				lift(liftBig);

			}

			if (t <= 1000)	{

				drive(127, 127);

				}	else	{

				drive(0, 0);

			}

			if (clawDone && liftDone)	{

				state++;

				t = 0;

			}

			break;

		case 2 :

			state++;

			break;

		case 3 :

			drive (0, 127);

			if (t > 650)	{

				state++;

				t = 0;

			}

			break;

		case 4 :

			drive (127, 127);

			if (t > 700)	{

				state++;

				t = 0;

			}

			break;

		case 5 :

			drive (-127, -127);

			if (t > 700)	{

				state++;

				t = 0;

			}

			break;


		case 6 :

			if (SensorValue[ifDisco] == 1)	{

				drive (0, -127);


				if (t > 650)	{

					state++;

					t = 0;

				}

				}	else	{

				drive(0,0);

			}

			break;


		case 7 :

			lift(1);

			drive (-127, -127);

			if (t > 500)	{

				state++;

				t = 0;

			}

			break;

		case 8 :

			claw(500);

			drive(60,-127);

			if (t > 450)	{

				state++;

				t = 0;

			}

			break;

		case 9 :

			drive (-127, -127);

			if (t > 600)	{

				state++;

				t = 0;

			}

			break;

		case 10 :

			drive (127, 127);
			claw(1300);

			if (t > 2000)	{

				state++;

				t = 0;

			}

			break;

		case 11 :

			drive (0, 0);
			claw(500);

			if (t > 500)	{

				state++;

				t = 0;

			}

			break;

		case 12 :

			drive(-127, -127);

			if (!liftDone)	{

				lift(liftBig);

			}

			if (t > 500)	{

				state++;

				t = 0;

			}

			break;

		case 13 :

			drive (-127, 127);

			if (t > 700)	{

				state++;

				t = 0;

			}

			break;

		case 14 :

			drive (127, 127);

			if (t > 1500)	{

				state++;

				t = 0;

			}

			break;

		case 15 :

			drive(0, 0);

			claw(clawHalf);

			if(clawDone)	{

				state++;

				clawDone = false;

			}

			break;

		default :

			break;

		}

		sleep(1);
		t++;

	}

}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{

	//int driveSpeed = 0;
	//int turnSpeed = 0;
	int driveL = 0, driveR = 0;

	const int threshold = 15;

	while (true)	{

		clawVal = SensorValue[s1];
		liftVal = SensorValue[s2];

		// Two Joystick Drive v2 - BAYAN EDITION

		driveL = vexRT[Ch3];
		driveR = vexRT[Ch2];

		if(abs(driveR) >= threshold)	{

			motor[d1] = driveR;

			}	else {

			motor[d1] = 0;

		}
		if(abs(driveL) >= threshold)	{

			motor[d2] = driveL;

			}else	{


			motor[d2] = 0;

		}

		if(vexRT[Btn6U] == 1)	{

			motor[g1] = 127;

			}	else if(vexRT[Btn6D] == 1)	{

			motor[g1] = -127;

			}	else	{

			motor[g1] = 0;

		}

		if (vexRT[Btn5U] == 1)	{

			motor[l1] = 127;
			motor[l2] = 127;
			motor[l3] = 127;
			motor[l4] = 127;
			motor[l6] = 127;

			}	else if (vexRT[Btn5D] == 1)	{

			motor[l1] = -127;
			motor[l2] = -127;
			motor[l3] = -127;
			motor[l4] = -127;
			motor[l6] = -127;

			}	else	{

			motor[l1] = 0;
			motor[l2] = 0;
			motor[l3] = 0;
			motor[l4] = 0;
			motor[l6] = 0;

		}

	}
}
