#pragma config(Sensor, in1,    lift,           sensorPotentiometer)
#pragma config(Sensor, in2,    grabber,        sensorPotentiometer)
#pragma config(Sensor, dgtl1,  rightDrive,     sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftDrive,      sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  cubeAuton,      sensorDigitalIn)
#pragma config(Sensor, dgtl12, switchDirection, sensorDigitalIn)
#pragma config(Motor,  port2,           grabR,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           liftL1,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           liftL2,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           driveL,        tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           driveR,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           liftR1,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           liftR2,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           grabL,         tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

// Global Variables

const int liftTop = 1200; // Position of lift when grabber should be opened in launch
const int liftMid = 1900; // Position of lift when half way to top
const int liftDown = 2500; // Position of lift when down
const int clawHalf = 2100; // Position of grabber where it is half open
const int clawClose = 2600; // Position of grabber when it is closed

bool openClaw = false; // Boolean to tell robot to open claw if necessary
bool manualOpen = false; // Disables automatically opening claw during launch

int state = 0; // State of autonomous

bool driveDone =  false, leftDone = false, rightDone = false; // When drive is done
bool liftDone =  false; // When lift is done
bool grabDone = false; // When grab is done

bool hold = false;

const int threshold = 15; // Threshold for how much the joystick must be pushed before activating drive
int liftPos = 0; // Holds potentiometer value for the lift position
int clawPos = 0; // Holds potentiometer value for the claw position
int leftPos = 0, rightPos = 0; // Holds shaft encoder value for left and right drive chains respectively

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/


void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

// Autonomous Functions - Fucntions used in the autonomous task to control robot

void drive(int left, int right, int speed)	{

	if (!driveDone)	{

		if(SensorValue[switchDirection] == 0)	{ // Switches direction of drive if desired by jumper in digital 12 port

			int temp;

			temp = left;
			left = right;
			right = temp;

		}


		int currentL = -SensorValue[leftDrive];
		int currentR = -SensorValue[rightDrive];

		int leeway = 2;

		if(currentL > (left + leeway))	{

			motor[driveL] = -speed;

			}	else	if(currentL < (left - leeway))	{

			motor[driveL] = speed;

			}	else	{

			motor[driveL] = 0;

			leftDone = true;
		}

		if(currentR > (right + leeway))	{

			motor[driveR] = -speed;

			}	else	if(currentR < (right - leeway))	{

			motor[driveR] = speed;

			}	else	{

			motor[driveR] = 0;

			rightDone =  true;

		}

		if(rightDone && leftDone)	{

			driveDone =  true;

			}	else	{

			driveDone = false;

		}

	}

}

void launch(int degree, int speed)	{

	int current = SensorValue[lift];

	int leeway = 20;

	if(current > (degree + leeway))	{

		motor[liftL1] = speed;
		motor[liftL2] = speed;
		motor[liftR1] = speed;
		motor[liftR2] = speed;

		}	else	if (current < (degree - leeway))	{

		motor[liftL1] = -speed;
		motor[liftL2] = -speed;
		motor[liftR1] = -speed;
		motor[liftR2] = -speed;

		}	else	{

		motor[liftL1] = 0;
		motor[liftL2] = 0;
		motor[liftR1] = 0;
		motor[liftR2] = 0;

		liftDone = true;

	}


}

void grab(int degree)	{

	int current = SensorValue[grabber];

	int leeway = 10;

	if(current > (degree + leeway))	{

		motor[grabL] = -127;
		motor[grabR] = -127;

		}	else	if (current < (degree - leeway))	{

		motor[grabL] = 127;
		motor[grabR] = 127;

		}	else	{

		motor[grabL] = 0;
		motor[grabR] = 0;

		grabDone = true;

	}

}

void checkLift()	{ // Checks if claw should start opening

	if((liftPos <= liftTop) && (liftPos > 500))	{

		openClaw = true;

		}	else	{

		openClaw = false;

	}

	if(openClaw && !manualOpen)	{

		if(clawPos <= 2300)	{

			motor[grabL] = 0;
			motor[grabR] = 0;

			openClaw = false;

			}	else	{

			motor[grabL] = -127;
			motor[grabR] = -127;


		}

		}	else	{

		openClaw = false;

	}

}

void holdLift()	{

	if(liftPos >= liftMid)	{

		motor[liftL1] = 90;
		motor[liftL2] = 90;
		motor[liftR1] = 90;
		motor[liftR2] = 90;

		}	else	{

		motor[liftL1] = 0;
		motor[liftL2] = 0;
		motor[liftR1] = 0;
		motor[liftR2] = 0;

	}

}

void resetVar()	{ // Resets autonomous booleans

	leftDone =  false;
	rightDone =  false;
	liftDone =  false;
	grabDone =  false;
	driveDone =  false;

}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

void auton1()	{ // First Autonomous program

	while (true)	{

		liftPos = SensorValue[lift];
		clawPos = SensorValue[grabber];
		leftPos = -SensorValue[leftDrive];
		rightPos = -SensorValue[rightDrive];

		switch (state)	{

		case 0:

			SensorValue[leftDrive] = 0;
			SensorValue[rightDrive] = 0;

			resetVar();

			state++;

			break;
		case 1:
			drive(10, 10, 127);
			if(driveDone)
			{
				resetVar();
				state ++;
			}
			break;

		case 2:

			grab(2400);

			if(grabDone)	{

				resetVar();

				state++;

			}

			break;

		case 3:

			drive(860, 860, 127);

			grab(clawHalf);

			if(driveDone)	{

				resetVar();

				state++;

				clearTimer(T1);

			}

			break;

		case 4:
			drive(860, 960, 127);
			grab(2550);
			if(grabDone || (time1[T1] > 500))
			{
				resetVar();

				state++;
			}



			break;

		case 5:

			motor[grabL] = 127;
			motor[grabR] = 127;

			state++;

			break;
		case 6: //turns left
			drive(420,1400, 127);
			launch(liftTop,80);
			if(driveDone)
			{
				resetVar();
				state++;
			}
			break;
		case 7:
			drive(-200, 800, 90);
			if(driveDone)	{

				resetVar();

				state++;

			}
			break;

		case 8:

			grab(clawHalf + 300);

			if (grabDone)	{

				resetVar();

				state++;
			}

			break;

		default:

			motor[driveL] = 0;
			motor[driveR] = 0;

			motor[liftL1] = 0;
			motor[liftL2] = 0;
			motor[liftR1] = 0;
			motor[liftR2] = 0;

			motor[grabL] = 0;
			motor[grabR] = 0;

			break;


		}

	}

}

void auton2()	{

	while (true)	{

		liftPos = SensorValue[lift];
		clawPos = SensorValue[grabber];
		leftPos = -SensorValue[leftDrive];
		rightPos = -SensorValue[rightDrive];

		switch (state)	{

		case 0:

			SensorValue[leftDrive] = 0;
			SensorValue[rightDrive] = 0;

			resetVar();

			state++;

			break;

		case 1:

			grab(clawHalf);

			if(grabDone)	{

				resetVar();

				state++;

			}

			break;

		case 2:

			drive(1850, 1850, 127);

			if(!liftDone)	{

				launch(1300,127);

			}

			if(driveDone)	{

				resetVar();

				state++;

			}

			break;

		default:

			motor[driveL] = 0;
			motor[driveR] = 0;

			motor[liftL1] = 0;
			motor[liftL2] = 0;
			motor[liftR1] = 0;
			motor[liftR2] = 0;

			motor[grabL] = 0;
			motor[grabR] = 0;

			break;



		}

	}

}
void auton3()	{ // Third Autonomous program

	while (true)	{

		liftPos = SensorValue[lift];
		clawPos = SensorValue[grabber];
		leftPos = -SensorValue[leftDrive];
		rightPos = -SensorValue[rightDrive];

		switch (state)	{

		case 0:

			SensorValue[leftDrive] = 0;
			SensorValue[rightDrive] = 0;

			resetVar();

			state++;

			break;
		case 1:
			drive(10, 10, 127);
			if(driveDone)
			{
				resetVar();
				state ++;
			}
			break;

		case 2:

			grab(2400);

			if(grabDone)	{

				resetVar();

				state++;

			}

			break;

		case 3:

			drive(860, 860, 127);

			grab(clawHalf);

			if(driveDone)	{

				resetVar();

				state++;

				clearTimer(T1);

			}

			break;

		case 4:
			drive(860, 960, 127);
			grab(2550);
			if(grabDone || (time1[T1] > 500))
			{
				resetVar();

				state++;
			}



			break;

		case 5:

			motor[grabL] = 127;
			motor[grabR] = 127;

			state++;

			break;
		case 6: //turns left
			drive(420,1400, 127);
			launch(liftTop,80);
			if(driveDone)
			{
				resetVar();
				state++;
			}
			break;
		case 7:
			drive(-200, 800, 90);
			if(driveDone)	{

				resetVar();

				state++;

			}
			break;

		case 8:

			drive(-500, 500, 80);

			if(!liftDone)	{

				launch(liftTop, 127);

			}

			if(liftPos <= 600)	{

				checkLift();

			}

			if (driveDone)	{

				resetVar();

				state++;
			}

			break;

		case 9:

			drive(1000, 1500, 127);

			grab(clawHalf);

			if(!liftDone)	{

				launch(liftDown, 127);

			}

			if(driveDone)	{

				resetVar();

				state++;

			}

			break;

		case 10:

			motor[grabL] = 127;
			motor[grabR] = 127;

			drive(1300, 2000, 127);

			if(driveDone)	{

				resetVar();

				state++;

			}

			break;

		case 11:

			motor[grabL] = 0;
			motor[grabR] = 0;

			drive(-500, 500, 127);

			if(driveDone)	{

				resetVar();

				state++;

			}



			break;

		default:

			motor[driveL] = 0;
			motor[driveR] = 0;

			motor[liftL1] = 0;
			motor[liftL2] = 0;
			motor[liftR1] = 0;
			motor[liftR2] = 0;

			motor[grabL] = 0;
			motor[grabR] = 0;

			break;


		}
	}
}

task autonomous()
{

	SensorValue[leftDrive] = 0;
	SensorValue[rightDrive] = 0;

	state = 0;

	if(SensorValue[cubeAuton] == 1)	{

		auton1(); // Cube auton

		}	else	{

		auton2(); // Drive forward auton

	}
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{

	SensorValue[leftDrive] = 0;
	SensorValue[rightDrive] = 0;

	while (true)
	{

		liftPos = SensorValue[lift];
		clawPos = SensorValue[grabber];
		leftPos = -SensorValue[leftDrive];
		rightPos = -SensorValue[rightDrive];

		if(abs(vexRT[Ch3]) > threshold)	{ // Turns left drive the same amount as specified by the joystick if the joystick value is over 15

			motor[driveL] = vexRT[Ch3];

			}	else	{

			motor[driveL] = 0;

		}

		if(abs(vexRT[Ch2]) > threshold)	{ // Turns right drive the same amount as specified by the joystick if the joystick value is over 15

			motor[driveR] = vexRT[Ch2];

			}	else	{

			motor[driveR] = 0;

		}

		if(vexRT[Btn5U]==1)	{

			motor[liftL1] = 127;
			motor[liftL2] = 127;
			motor[liftR1] = 127;
			motor[liftR2] = 127;

			hold = false;

			}	else	if (vexRT[Btn5D] ==1)	{

			motor[liftL1] = -127;
			motor[liftL2] = -127;
			motor[liftR1] = -127;
			motor[liftR2] = -127;

			hold = false;

			}	else	{

			motor[liftL1] = 0;
			motor[liftL2] = 0;
			motor[liftR1] = 0;
			motor[liftR2] = 0;

		}

		if(vexRT[Btn6D]==1)	{

			motor[grabL] = 127;
			motor[grabR] = 127;

			}	else	if (vexRT[Btn6U] ==1)	{

			motor[grabL] = -127;
			motor[grabR] = -127;

			}	else	{

			motor[grabL] = 0;
			motor[grabR] = 0;
		}

		if(vexRT[Btn7L] == 1)	{

			manualOpen = false;

			}	else if(vexRT[Btn7R] == 1)	{

			manualOpen = true;

		}

		if(vexRT[Btn8L] == 1)	{

			hold = false;

			}	else if(vexRT[Btn8R] == 1)	{

			hold = true;

		}

		if(hold)	{

		holdLift();

	}

		checkLift();

	}
}
