#pragma config(Sensor, dgtl11,  p1,             sensorDigitalOut)
#pragma config(Sensor, dgtl2,  p2,             sensorDigitalOut)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)	{

		if (VEXRT[Btn5D] == 1)	{

			SensorValue[p1] = 1;

			}	else	{

			SensorValue[p1] = 0;

		}

	}

}
