#pragma config(Sensor, in1,    lift,           sensorPotentiometer)
#pragma config(Sensor, in2,    grabber,        sensorPotentiometer)
#pragma config(Sensor, dgtl1,  rightDrive,     sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftDrive,      sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  manual,         sensorDigitalOut)
#pragma config(Motor,  port2,           grabR,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           liftL1,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           liftL2,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           driveL,        tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           driveR,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           liftR1,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           liftR2,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           grabL,         tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

// Global Variables

const int liftTop = 770; // Position of lift when grabber should be opened in launch
const int liftMid = 1500; // Position of lift when half way to top
const int liftDown = 2500; // Position of lift when down

const int clawHalf = 2000; // Position of grabber where it is half open
const int clawClose = 2600; // Position of grabber when it is closed

bool openClaw = false; // Boolean to tell robot to open claw if necessary
bool manualOpen = false; // Disables automatically opening claw during launch

int state = 0; // State of autonomous

bool driveDone =  false, leftDone = false, rightDone = false; // When drive is done
bool liftDone =  false; // When lift is done
bool grabDone = false; // When grab is done

const int threshold = 15; // Threshold for how much the joystick must be pushed before activating drive
int liftPos = 0; // Holds potentiometer value for the lift position
int clawPos = 0; // Holds potentiometer value for the claw position
int leftPos = 0, rightPos = 0; // Holds shaft encoder value for left and right drive chains respectively

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/


void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

// Autonomous Functions - Fucntions used in the autonomous task to control robot

void drive(int left, int right)	{

	int currentL = -SensorValue[leftDrive];
	int currentR = -SensorValue[rightDrive];

	int leeway = 2;

	if(currentL > (left + leeway))	{

		motor[driveL] = -127;

		}	else	if(currentL < (left - leeway))	{

		motor[driveL] = 127;

		}	else	{

		motor[driveL] = 0;

		leftDone = true;
	}

	if(currentR > (right + leeway))	{

		motor[driveR] = -127;

		}	else	if(currentR < (right - leeway))	{

		motor[driveR] = 127;

		}	else	{

		motor[driveR] = 0;

		rightDone =  true;

	}

	if(rightDone && leftDone)	{

		driveDone =  true;

		}	else	{

		driveDone = false;

	}

}

void launch(int degree)	{

	int current = SensorValue[lift];

	int leeway = 10;

	if(current > (degree + leeway))	{

		motor[liftL1] = 127;
		motor[liftL2] = 127;
		motor[liftR1] = 127;
		motor[liftR2] = 127;

		}	else	if (current < (degree - leeway))	{

		motor[liftL1] = -127;
		motor[liftL2] = -127;
		motor[liftR1] = -127;
		motor[liftR2] = -127;

		}	else	{

		motor[liftL1] = 0;
		motor[liftL2] = 0;
		motor[liftR1] = 0;
		motor[liftR2] = 0;

		liftDone = true;

	}

}

void grab(int degree)	{

	int current = SensorValue[grabber];

	int leeway = 10;

	if(current > (degree + leeway))	{

		motor[grabL] = -127;
		motor[grabR] = -127;

		}	else	if (current < (degree - leeway))	{

		motor[grabL] = 127;
		motor[grabR] = 127;

		}	else	{

		motor[grabL] = 0;
		motor[grabR] = 0;

		grabDone = true;

	}

}

void checkLift()	{ // Checks if claw should start opening

	if(liftPos <= liftTop)	{

		openClaw = true;

	}

	if(openClaw && !manualOpen)	{

		if(clawPos <= clawHalf)	{

			motor[grabL] = 0;
			motor[grabR] = 0;

			openClaw = false;

			}	else	{

			motor[grabL] = -127;
			motor[grabR] = -127;


		}

	}

}

void resetVar()	{ // Resets autonomous booleans

	leftDone =  false;
	rightDone =  false;
	liftDone =  false;
	grabDone =  false;
	driveDone =  false;

}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

void auton1()	{ // First Autonomous program

	while (true)	{

		liftPos = SensorValue[lift];
		clawPos = SensorValue[grabber];
		leftPos = -SensorValue[leftDrive];
		rightPos = -SensorValue[rightDrive];

		switch (state)	{

		case 0:

			SensorValue[leftDrive] = 0;
			SensorValue[rightDrive] = 0;

			resetVar();

			state++;

			break;

		case 1:

			grab(clawHalf);

			if(grabDone)	{

				resetVar();

				state++;

			}

			break;

		case 2:

			drive(760, 760);

			if(driveDone)	{

				resetVar();

				state++;

			}

			break;

		case 3:

			grab(2250);

			if(grabDone)	{

				resetVar();

				state++;

			}

			break;

		case 4:

			drive(1450, 1450);

			launch(liftMid);

			if(driveDone)	{

				resetVar();

				state++;

			}

			break;

		case 5:

			drive(800, 1950);

			if(driveDone)	{

				resetVar();

				state++;

			}

			break;

		case 6:

			drive(0, 1150);

			checkLift();

			if (leftPos <= 600)	{

				launch(liftTop);

			}

			if(driveDone)	{

				resetVar();

				state++;

			}

			break;

		case 7:

			launch(liftDown);

			if(liftDone)	{

				resetVar();

				state++;

			}

			break;

		case 8:

			drive(1150, 2300);

			if(driveDone)	{

				resetVar();

				state++;

			}

			break;

		case 9:

			drive(650, 1650);

			grab(clawClose);

			if(driveDone && grabDone)	{

				resetVar();

				state++;

			}

			break;

		case 10:

			drive(20, 1020);

			launch(liftTop);

			if(driveDone)	{

				resetVar();

				state++;

			}

			break;

		case 11:

			launch(liftDown);

			if(liftDone)	{

				resetVar();

				state++;

			}

			break;

		case 12:

			drive(1150, 2300);

			if(driveDone)	{

				resetVar();

				state++;

			}

			break;

		case 13:

			drive(650, 1650);

			grab(clawClose);

			if(driveDone && grabDone)	{

				resetVar();

				state++;

			}

			break;

		case 14:

			drive(20, 1020);

			launch(liftTop);

			if(driveDone)	{

				resetVar();

				state++;

			}

			break;

		default:

			motor[driveL] = 0;
			motor[driveR] = 0;

			motor[liftL1] = 0;
			motor[liftL2] = 0;
			motor[liftR1] = 0;
			motor[liftR2] = 0;

			motor[grabL] = 0;
			motor[grabR] = 0;

			break;


		}

	}

}

task autonomous()
{

	SensorValue[leftDrive] = 0;
	SensorValue[rightDrive] = 0;

	state = 0;

	auton1();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{

	SensorValue[leftDrive] = 0;
	SensorValue[rightDrive] = 0;

	while (true)
	{

		liftPos = SensorValue[lift];
		clawPos = SensorValue[grabber];
		leftPos = -SensorValue[leftDrive];
		rightPos = -SensorValue[rightDrive];

		if(abs(vexRT[Ch3]) > threshold)	{ // Turns left drive the same amount as specified by the joystick if the joystick value is over 15

			motor[driveL] = vexRT[Ch3];

			}	else	{

			motor[driveL] = 0;

		}

		if(abs(vexRT[Ch2]) > threshold)	{ // Turns right drive the same amount as specified by the joystick if the joystick value is over 15

			motor[driveR] = vexRT[Ch2];

			}	else	{

			motor[driveR] = 0;

		}

		if(vexRT[Btn5U]==1)	{

			motor[liftL1] = 127;
			motor[liftL2] = 127;
			motor[liftR1] = 127;
			motor[liftR2] = 127;

			}	else	if (vexRT[Btn5D] ==1)	{

			motor[liftL1] = -127;
			motor[liftL2] = -127;
			motor[liftR1] = -127;
			motor[liftR2] = -127;

			}	else	{

			motor[liftL1] = 0;
			motor[liftL2] = 0;
			motor[liftR1] = 0;
			motor[liftR2] = 0;

		}

		if(vexRT[Btn6D]==1)	{

			motor[grabL] = 127;
			motor[grabR] = 127;

			}	else	if (vexRT[Btn6U] ==1)	{

			motor[grabL] = -127;
			motor[grabR] = -127;

			}	else	{

			motor[grabL] = 0;
			motor[grabR] = 0;
		}

		if(vexRT[Btn7D] == 1)	{

			if(manualOpen)	{

				manualOpen = false;

				}	else	{

				manualOpen = true;

			}

		}

		checkLift();

	}
}
