#pragma config(Motor,  port2,           g1,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           d2,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           l3,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           l6,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           l4,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           l1,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           l2,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           d1,            tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	int driveSpeed = 0;
	int turnSpeed = 0;

	const int threshold = 15;

	while (true)	{
		// One Joystick Drive
		/*
		driveL = vexRT[Ch1] + vexRT[Ch2];
		driveR = vexRT[Ch1] - vexRT[Ch2];

		if((abs(driveL) >= threshold) || (abs(driveR) > threshold))	{

		motor[d1] = driveL;
		motor[d2] = driveR;

		}	else	{

		motor[d1] = 0;
		motor[d2] = 0;

		}
		*/

		// Two Joystick Drive

		turnSpeed = vexRT[Ch4];
		driveSpeed = vexRT[Ch2];

		if(abs(driveSpeed) >= threshold)	{

			motor[d1] = -driveSpeed;
			motor[d2] = -driveSpeed;

			}	else if(abs(turnSpeed) >= threshold)	{

			motor[d1] = turnSpeed;
			motor[d2] = -turnSpeed;

			}else	{

			motor[d1] = 0;
			motor[d2] = 0;

		}

		if(vexRT[Btn6U] == 1)	{

			motor[g1] = 127;

			}	else if(vexRT[Btn6D] == 1)	{

			motor[g1] = -127;

			}	else	{

			motor[g1] = 0;

		}

		if (vexRT[Btn5U] == 1)	{

			motor[l1] = 127;
			motor[l2] = 127;
			motor[l3] = 127;
			motor[l4] = 127;

			}	else if (vexRT[Btn5D] == 1)	{

			motor[l1] = -127;
			motor[l2] = -127;
			motor[l3] = -127;
			motor[l4] = -127;

			}	else	{

			motor[l1] = 0;
			motor[l2] = 0;
			motor[l3] = 0;
			motor[l4] = 0;

		}

	}

}
