#pragma config(Motor,  port2,           g1,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           d2,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           l3,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           l6,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           l4,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           l1,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           l2,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           d1,            tmotorVex393HighSpeed_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"

task main()
{

	//int driveSpeed = 0;
	//int turnSpeed = 0;
	int driveL = 0, driveR = 0;

	const int threshold = 15;

	while (true)	{

		// Two Joystick Drive v2 - BAYAN EDITION

		driveL = vexRT[Ch3];
		driveR = vexRT[Ch2];

		if(abs(driveR) >= threshold)	{

			motor[d1] = driveR;

			}	else {

			motor[d1] = 0;

		}
		if(abs(driveL) >= threshold)	{

			motor[d2] = driveL;

			}else	{


			motor[d2] = 0;

		}

		if(vexRT[Btn6U] == 1)	{

			motor[g1] = 127;

			}	else if(vexRT[Btn6D] == 1)	{

			motor[g1] = -127;

			}	else	{

			motor[g1] = 0;

		}

		if (vexRT[Btn5U] == 1)	{

			motor[l1] = 127;
			motor[l2] = 127;
			motor[l3] = 127;
			motor[l4] = 127;
			motor[l6] = 127;

			}	else if (vexRT[Btn5D] == 1)	{

			motor[l1] = -127;
			motor[l2] = -127;
			motor[l3] = -127;
			motor[l4] = -127;
			motor[l6] = -127;

			}	else	{

			motor[l1] = 0;
			motor[l2] = 0;
			motor[l3] = 0;
			motor[l4] = 0;
			motor[l6] = 0;

		}

	}
}
